{% set version = "0.6.1" %}

package:
  name: jupyter_nbextensions_configurator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_nbextensions_configurator/jupyter_nbextensions_configurator-{{ version }}.tar.gz
  sha256: 4b9e1270ccc1f8e0a421efb8979a737f586813023a4855b9453f61c3ca599b82

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyter-nbextensions_configurator = jupyter_nbextensions_configurator.application:main


requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jupyter_contrib_core >=0.3.3
    - jupyter_core
    - notebook >=6.0
    - pyyaml
    - tornado
    - traitlets

test:
  imports:
    - jupyter_nbextensions_configurator
    - jupyter_nbextensions_configurator.application
  requires:
    - pip
  commands:
    - jupyter nbextensions_configurator --help
    - jupyter nbextensions_configurator enable --help
    - jupyter nbextensions_configurator disable --help
    - pip check

about:
  summary: A server extension for jupyter notebook providing configuration interfaces for notebook extensions (nbextensions).
  home: https://github.com/jupyter-contrib/jupyter_nbextensions_configurator
  license_file: LICENSE.txt
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - jcb91
    - xhochy
