travis:
  secure:
    BINSTAR_TOKEN: DFBBhsMFjyhyv4Da3UAy75BAjJMNrYmY90CG4Pecjp7h8WDfJoK/+mMxXfMA3eBJHWPWiBU2BKffn/5wWry6WXCYZ/ucI9aFQnlnFYvqteJt3Ot8MODbGZJPbeksTqLV43MFVu85sALDLxwa5y/bTC1rc4YAfNe8PGdk1uhVsLK2N4EmDEnoaMUYtNT6FTX99/mU21EIxhWDV0Ne/nx4jsGNCcOs9Q7hi3plLwwaOWLu+qVOSNmUv2S1M8KRljNyYWnPB7jdeQJaChp7ITzr+h9tRMRyVxu0HQi6JKDsSQNdfepJBOxW/iS1b3lUhYlo9/W0/44HuwO4ABc8QxpW8hrSt3P/ub95r+x8EbU3hyciDsZv3hd4pmACHKV8KlObynA2udyFwKWKh8mlVDHxYfFUNelMrA35AltN6p0FOolnizQTWrChRhAzSVJ+aymoNYyk6BJ38E+ZT92rS9AuLGwSLvuzgfEgdN93XYK2Obh8/vWEL+0oSIIzY5in20BjzZ3t4AktMSG4VgxIDbQvUfCXusbLxM9hQYkTnUqq6B3CB2x4uyFEyQ0jAyJwGE25JDBk03L7malCoE1vSRLkAoep0nxD2BkTYhVq4YzvN4w98AMoEwUcVbNApieLt2/hb1KsCBAl8U46W8OclcjceniQmaRhdPToMNk2tBCihAw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
