travis:
  secure:
    BINSTAR_TOKEN: IhaxhAtHuCvsF5LtoavOlFLDz006n+HJQY+rJmQb6ZgNnHtf247JNx8fQ1G/tMidRoMJ8aJ7oVTYTZVpLfnACoSuZgL3E2meWnCoghSlydA0Ce47TjqXSuvZUvY/YY0rvhSEGIp+HgRIu+zO3Gi46iYFcE1eBfEOUr6F11adDwEbsHXagpo17wvcwT2ypbw4DPz4X16IYFq8BdFr5o9p6B2sApQLHCUJB6/bFMJW/Zzvvs8jwntaQNv5TvuwG2Lrr3HLSEXrRaEcKDL0vUNiMUYGPr7+EPaW5/7rrnaiBqKwPuo5dwTQrROIFHFNYlT38ylFqD9P3H5WCQPVO2t2EEE1vpf8LqnsK3wSqafp0c+zV653T9bIRE60QG0h3OpEzuC8q/fDw/R2mxMqi0BZMrsYiU4LC6pXpzOuD13vh2Y6rPezQ7E2qYft3Hxngf3WpDfcsVgkF9lOTQYS+GD5clvCvig7234NWik5yBq/BkqY3zqbnwfUZvzTx8UFaQOIAqUJ8T7AGfynC+uKACsU9r1M7CmT+ZM0Nanm2vecDW4I9Ag8ns0Q/NkFc58u5HjZ1NLm39+keZy3t0Hy/m6YoB2I2zJ9zdLCzRzme+IMi+wSs96RcjPW6nMpYRTh9Q7lUNp0axTPjj6AOh03njgD92mU290xXIJWtgdwDai83dw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
