travis:
  secure:
    BINSTAR_TOKEN: ER0fxW6PQ/kwmNYguluMWi3+MhDccBHwxH75sCiVO5cl4nmmXplBzvqiNjbuCUVgEcvjNQNFtJZJtKcn+mfLwH+vJybhHU7bXNsFsttAfetkaJRl9MQ6LBE97k1+nhddYMbNV/IDGXTg+NwlsTecZkbA2/ngdtwXaaZ8vcsbsRWBoWpvDnQf+JK6oqR062Mdhgee5fN5GEL8x1woJtOdbzbtNCtkweRYAQcsE5BjiTjMhrJraXcRSk0byZdUzZ3Gq9gsstrh5sVtHBNLL7cSr9ArXErdls6aVJ1lLIk3Yzhbx8Vjb60qtq0lDGanu25Nx2+Jx9svKW1gh8PkLyHv0WiWSagXJgRQfSvf8YMjfnFr/GgiFTyTnVZTQ5tuxY007KwAHuplAd/1yNp8/LZIhlKBA/xDPmUgLXX9MJ2Jh11tixGsl6VLQoXPbTA/WURyynkNgrkTP+BBpy3OPICLvHiuFayg7YA4Ha2xQKyJjCGAvCfgFcBGEExzqkOsHMoo5G/bMdtcDSeL66yGbBsmYVWReH++o24nfMbgWSBQK7+GVYvZoXuKQQT1zVwhm33OEnMa2uhMiNGd38mtseEitH2697XSKL8Q736Fwb+oLlX8tOqA+yFdiUMmugWyjOAayDGFOQ0k6GfAkGLUZ8oU7/xv/su0df2ZjL5lsRRX+WM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
